# Generated by Django 4.0.6 on 2022-08-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedfile',
            name='upload_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
