# Generated by Django 4.0.6 on 2022-08-12 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2022, 8, 12, 20, 6, 59, 15495))),
                ('saved', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
