# Generated by Django 4.0.6 on 2022-08-12 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedfile',
            name='upload_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 8, 12, 19, 30, 5, 439018)),
        ),
    ]
