# Generated by Django 4.0.6 on 2022-08-08 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_chunkedfile_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedfile',
            name='upload_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 8, 8, 23, 5, 56, 391952)),
        ),
    ]
